### ISSUE TITLE
Scanning music directory does not work on mounted network drive.

### ISSUE THREAD

**Issue by bradx954** [IrosTheBeggar/mStream#194] opened 2019-07-06 02:08 UTC
Trying to get this to work with a onedrive music folder mounted with rclone. It runs but does not find any music. Is this a bug or is it outside of the scope of how this software can work? Is there anyway to make this work?

Log:
`{"message":"File scan started on /home/bbaago/OneDrive/Music","level":"info","timestamp":"2019-07-06T01:55:52.214Z"}
{"message":"File scan message: database saved","level":"info","timestamp":"2019-07-06T01:55:52.672Z"}
{"message":"File scan completed with code 0","level":"info","timestamp":"2019-07-06T01:55:52.682Z"}`

**Comment by IrosTheBeggar** [comment] 2019-07-06 16:48
I never tested mStream on network drives.  Does the file explorer function work in the Web UI?

**Comment by bradx954** [comment] 2019-07-06 16:50
No it either shows nothing or I get "Server Call Failed".

**Comment by IrosTheBeggar** [comment] 2019-07-06 16:55
Ok, that means the file system calls are failing when using the network drive.  You mentioned onedrive, is this on a Windows computer?

**Comment by bradx954** [comment] 2019-07-06 16:57
No its a ubuntu server. Obviously not an ideal setup so I would understand if this is not possible.

**Comment by IrosTheBeggar** [comment] 2019-07-06 17:03
Yea that’s a hard one.  I don’t have the time to replicate that setup and even if I did it might be something I can’t solve.

Thanks for checking out mStream. I’ll leave this ticket open incase someone else has some experience with this

**Comment by bradx954** [comment] 2019-07-10 00:12
I think I fixed the issue with a newer version of rclone. Running the scan now. One thing I am noticing is a lot of network traffic over a long period of time. Do you know if the scanning process goes through the whole file?

**Comment by IrosTheBeggar** [comment] 2019-07-12 15:05
@bradx954 The scan parses every file for metadata and then makes an md5 hash of it.  So yea, it does a lot of file parsing.  After the file is added to the DB, the scan only checks for its created and modified time to look for updates

**Comment by Hakker** [comment] 2019-07-12 19:15
It's very slow when it's a local network as well.  NFS or SMB doesn't seem to matter. Doesn't matter if you symlink it in windows or make a mapped drive it's scanning it and works technically but I need 2-3 minutes of searching for every folder. Doesn't matter how tiny it's unusable with 1500 files, but the amount of files probably doesn't even matter.

**Comment by IrosTheBeggar** [comment] 2019-07-21 05:28
mStream was designed to work with local files. While it can do everything through network drives, this is not what it was designed for. 

You should consider running mStream on the same computer you are running your Samba server or network drive on for best results.  I'm closing this ticket since there's nothing I can really do about this

**Closed as completed by IrosTheBeggar** 2019-07-21 05:28 UTC

**Comment by Hakker** [comment] 2019-07-21 12:17
Sad to hear that. That makes this project unusable for people who have their stuff on a NAS, fileserver, Gdrive or Onedrive and not a replacement for any Sonic solution in that regard.
Too bad to hear it, but I wish you good luck with your project.
