### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#101] opened 2018-05-16 14:17 UTC
Sorry for keeping adding stuff

when the database is created (mstream.db) than you will see the number of songs added to the db:

![image](https://user-images.githubusercontent.com/250108/40122549-5988bc9a-5924-11e8-872e-2a503bce2120.png)

but this number is not being updated. Only when stopping mstream and restarting it this number is refreshed.

For me is important following:

- database is representing the actual contents of the folders 
- when files are removed they should be (at least) 1x a day be refreshed and/or removed from the database
- when files are added to a folder within the master folder it should be added to the database (at least 1x a day)

**Comment by IrosTheBeggar** [comment] 2018-05-16 15:32
This is something I've already been looking into.  There are some libraries that can be used to keep the DB in sync with the filesystem.  The problem is they're either unreliable or need additional software installed that makes the installation process a lot less user friendly.  You can see a list of those libraries in this ticket: https://github.com/IrosTheBeggar/mStream/issues/77


I've got a local dev branch that has a updateOnInterval function that can be set with the command line.  I'll get that cleaned up and committed sometime this weekend.

**Comment by IrosTheBeggar** [comment] 2018-06-04 06:13
I added the code for scanning on an interval.  You can set it in the JSON config with: 

```
  "database_plugin":{
    "dbPath":"/path/to/loki.db",
    "interval": "1.5"
  },
```

the interval is set in hours.  And you need quotes around it if it's a decimal

**Comment by IrosTheBeggar** [comment] 2018-06-04 06:16
Closing this ticket since more advanced file system handling is handled in #77

**Closed as completed by IrosTheBeggar** 2018-06-04 06:16 UTC

**Comment by aroundmyroom** [comment] 2018-06-04 07:30
ok, back to using json file, with interval now . .
every 12 hours .. But I am not sure it will scan my whole database, any way how we can check that?
the initial scan would be +12 hours btw will the scan not scan when previous scan is still running?

**Comment by IrosTheBeggar** [comment] 2018-06-04 14:51
If a scan is in progress, it will block any new scan calls.  A new scan cannot be started until the previous one ends.  This prevents file collisions and prevents mStream from eating up all the disk I/O.  I'l look into adding some logging so we can see where exactly the DB is failing in your case
