### ISSUE TITLE
Request: allow folders within scan folder to be not indexed

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#163] opened 2018-12-03 09:24 UTC
ie.
I have all my music in
d:\myMusic
I want all music indexed but not
d:\myMusic\Thisfoldernot
d:\myMusic\Thisfolderalsonot

all other folders can be indexed.
Right now if you do not want to have it indexed you need to modify our own library/directory structure so that it is not in the main folder structure.

In this way the DJ service etc. will not play them
There could be a flag to show the folder yes/no in the folder list as well.

'only show indexed folders'
'do show all folders '

etc.

**Comment by IrosTheBeggar** [comment] 2019-01-30 21:01
Closing since this is functionally a duplicate of https://github.com/IrosTheBeggar/mStream/issues/169

**Closed as completed by IrosTheBeggar** 2019-01-30 21:01 UTC
