### ISSUE TITLE
Track not updated when song has no metadata

### ISSUE THREAD

**Issue by godlessendeavor** [IrosTheBeggar/mStream#274] opened 2020-07-26 09:13 UTC
Hi,

When playing a list of mp3 songs sometimes I have some with no metadata. When the player plays these songs the track name will not be updated anymore (tags are empty as expected, but the track should reflect the name of the file).

This happens because of the following error:
`DOMException: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.`

Specifically this line: `var source = audioCtx.createMediaElementSource(lPlayer.playerObject._sounds[0]._node);`

Looks like the Howler player has not cleaned up that node. 
Is it possible to fix it?

**Comment by aroundmyroom** [comment] 2020-07-29 13:41
saw this issue, but thought it was due to one of my own changes ..  can tell that I have same.

**Comment by IrosTheBeggar** [comment] 2021-01-03 22:47
@godlessendeavor & @aroundmyroom 

is this problem still happening?  If so, can you send me a file that's causing it?

Sorry for the delay.  I promise there will be a more progress on mstream in 2021

**Comment by aroundmyroom** [comment] 2021-01-04 07:04
yes it is still happening in the version I am running now .. (one of the first 5.x releases). 
I need to setup a new VM to be able to test the new version where a lot has been changed. (end of december updates)

To reproduce:
start playing the MP3, than press DJ mode and after the song has ended (you can skip to the end as this example is 1 hour long)
you will see that the info in the GUI is not updated: example file:
https://we.tl/t-AjoMDcRoER

**Comment by xander89ab** [comment] 2021-01-13 13:02
I support the topic-starter with same issue. 
Thought it's only mine case with incorrect meta-data of certain tracks.

**Comment by IrosTheBeggar** [comment] 2021-02-28 04:53
This should be fixed in the latest commit. Let me know if it works

**Comment by aroundmyroom** [comment] 2021-02-28 12:34
looks good

**Closed as completed** 2021-02-28 14:42 UTC
